[default]
port = 8000
address = "0.0.0.0"
log_level = "debug"
# Cache duration in days
instagram_cache_duration = 1
# Scraping timeout in seconds
timeout = 30
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
# Instagram usernames that are allowed to be scraped (comment out to allow all)
# Better use env INSTAGRAM_USERNAME_WHITELIST
#instagram_username_whitelist = ["user1", "user2", "user3"] 
# Instagram session cookies for authenticated requests (helps bypass rate limits)
# Better use env INSTAGRAM_COOKIES
#instagram_cookies = "sessionid=YOUR_SESSION_ID; ds_user_id=YOUR_USER_ID; csrftoken=YOUR_CSRF_TOKEN" 
# List of proxies to use for scraping (rotated randomly)
# Format: "protocol://username:password@host:port" or "protocol://host:port"
# Supported protocols: http, https, socks5
# Examples: ["http://user:pass@proxy1.example.com:8080", "socks5://proxy2.example.com:1080"]
# Better use env PROXIES
#proxies = ["http://proxy1.example.com:8080", "socks5://proxy2.example.com:1080"] 