name: Scrapn Build

on:
  push:
    branches:
      - 'develop'
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
 
      - 
        name: Setup cache
        uses: Swatinem/rust-cache@v2 
      - 
        name: Run tests
        run: cargo test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get tag name
        uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - 
        name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branchName
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/zippy1978/scrapn
      - 
        name: Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BUILD_NUMBER=${{ github.run_number }}
          tags: ${{ steps.meta.outputs.tags }}
